version: '3.4'

services:
  poleserver:
    env_file:
      - ./.env
    depends_on:
      - poleservermongo

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      NODE_ENV: production
      MONGO_EXPRESS_CONFIG_URL: $MONGO_EXPRESS_CONFIG_URL
    # deploy:
    #   mode: replicated
    #   replicas: 6
    ports:
      - $NODE_PORT:$DOCKER_PORT
    volumes:
      - .:/usr/src


  poleservermongo:
    image: mongo
    container_name: poleservermongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
    ports:
      - $MONGO_DB_DOCKER_PORT:$MONGO_DB_LOCAL_PORT
    volumes:
      - poleserver:/data/db:rw
      
volumes:
  poleserver:

